#!/usr/bin/env python3
"""Generate immutable checkpoint ROMs and integer golden vectors.

Use --data to evaluate the full public test split. This command does not train,
calibrate, or change quantization. PyTorch is used only to enumerate the existing
SW float32 nonlinear definition and optionally compare its QDQ graph directly.
"""

import argparse
import json
from pathlib import Path
import sys
import time

import numpy as np

from integer_model import EXPORT, GENERATED, LAYERS, ROOT, IntegerModel, file_hash, metrics, quantize_input


def make_tables(export):
    sys.path.insert(0, str(ROOT / "sw"))
    import torch
    from model import EXP_KNOTS, SILU_KNOTS, piecewise
    from quantize import quantizeTensor
    torch.set_num_threads(2)
    profile = json.loads((export / "quantization.json").read_text())
    tables = []
    definitions = []
    for block in range(2):
        for source, target, operation in [("conv", "x", "silu"), ("gateInput", "gate", "silu"), ("expInput", "Abar", "exp")]:
            prefix = "blocks.%d." % block
            input_exp = int(profile["nodes"][prefix + source]["exponent"])
            output_exp = int(profile["nodes"][prefix + target]["exponent"])
            inputs = torch.arange(-128, 128, dtype=torch.float32) * (2.0 ** input_exp)
            values = piecewise(inputs, SILU_KNOTS if operation == "silu" else EXP_KNOTS, operation)
            tables.append(quantizeTensor(values, output_exp).numpy().astype(np.int8))
            definitions.append({"block": block, "input": prefix + source, "output": prefix + target,
                                "operation": operation, "inputExponent": input_exp, "outputExponent": output_exp})
    return np.stack(tables), {"backend": "torch " + torch.__version__, "dtype": "float32", "definition": "sw/model.py:piecewise",
                             "addressOrder": "signed inputs -128 through 127", "tables": definitions}


def bsv_rom(name, signature, choices, width):
    lines = ["function Int#(8) " + name + "(" + signature + ");", "\tInt#(8) result = 0;"]
    for condition, address_name, entries in choices:
        lines.append("\tif ( " + condition + " ) begin")
        lines.append("\t\tcase ( " + address_name + " )")
        for address, value in entries:
            if value:
                lines.append("\t\t\t%d'd%d: result = %d;" % (width, address, value))
        lines.extend(["\t\t\tdefault: result = 0;", "\t\tendcase", "\tend"])
    lines.extend(["\treturn result;", "endfunction", ""])
    return lines


def bsv_integer_function(name, signature, variable, values):
    lines = ["function Integer " + name + "(" + signature + ");", "\tInteger result = 0;"]
    for key, value in values:
        literal = json.dumps(key) if isinstance(key, str) else str(key)
        lines.append("\tif ( " + variable + " == " + literal + " ) result = " + str(value) + ";")
    return lines + ["\treturn result;", "endfunction", ""]


def write_bsv(model):
    lines = ["// Generated by reference/generate.py from the verified SW INT8 export.",
             "// Weights are fixed distributed ROM logic, four output-channel banks.",
             "package SwayParameters;", "", "import Vector::*;", ""]
    banks = []
    biases = []
    for layer, (output, input_name, weight_name, bias_name) in enumerate(LAYERS):
        weight = model.parameters[weight_name]
        for lane in range(4):
            entries = []
            for group in range((len(weight) + 3) // 4):
                row = group * 4 + lane
                for column in range(weight.shape[1]):
                    entries.append((group * weight.shape[1] + column, int(weight[row, column]) if row < len(weight) else 0))
            banks.append(("layerId == %d && lane == %d" % (layer, lane), "addr", entries))
        if bias_name:
            biases.append(("layerId == %d" % layer, "row", list(enumerate(model.parameters[bias_name].tolist()))))
    lines += bsv_rom("linearWeight", "Integer layerId, Integer lane, Bit#(13) addr", banks, 13)
    lines += bsv_rom("linearBias", "Integer layerId, Bit#(9) row", biases, 9)
    for function, index in [("layerInputScale", 1), ("layerWeightScale", 2), ("layerOutputScale", 0)]:
        lines += bsv_integer_function(function, "Integer layerId", "layerId", [(layer, model.exponent(names[index])) for layer, names in enumerate(LAYERS)])
    lines += bsv_integer_function("layerBiasScale", "Integer layerId", "layerId", [(layer, model.exponent(names[3]) if names[3] else 0) for layer, names in enumerate(LAYERS)])
    lines += ["function Bool layerHasBias(Integer layerId);", "\tBool result = False;"]
    for layer, names in enumerate(LAYERS):
        if names[3]:
            lines.append("\tif ( layerId == %d ) result = True;" % layer)
    lines += ["\treturn result;", "endfunction", ""]
    lines += bsv_integer_function("nodeScale", "String name", "name", [(name, node["exponent"]) for name, node in model.profile["nodes"].items()])
    lines += ["function Integer blockScale(Integer blockId, String suffix);", "\tInteger result = 0;"]
    for block in range(2):
        lines.append("\tif ( blockId == %d ) begin" % block)
        prefix = "blocks.%d." % block
        for name, node in model.profile["nodes"].items():
            if name.startswith(prefix):
                lines.append("\t\tif ( suffix == %s ) result = %d;" % (json.dumps(name[len(prefix):]), node["exponent"]))
        lines.append("\tend")
    lines += ["\treturn result;", "endfunction", ""]
    for function, parameter in [("normWeight", "normWeight"), ("normBias", "normBias"), ("convBias", "convBias"), ("directD", "D")]:
        choices = [("blockId == %d" % block, "channel", list(enumerate(model.parameters["blocks.%d.%s" % (block, parameter)].tolist()))) for block in range(2)]
        lines += bsv_rom(function, "Integer blockId, Bit#(6) channel", choices, 6)
    choices = []
    for block in range(2):
        for tap in range(4):
            choices.append(("blockId == %d && tap == %d" % (block, tap), "channel", list(enumerate(model.parameters["blocks.%d.convWeight" % block][:, 0, tap].tolist()))))
    lines += bsv_rom("convWeight", "Integer blockId, Integer tap, Bit#(6) channel", choices, 6)
    choices = []
    for block in range(2):
        for state in range(8):
            choices.append(("blockId == %d && n == %d" % (block, state), "channel", list(enumerate(model.parameters["blocks.%d.A" % block][:, state].tolist()))))
    lines += bsv_rom("stateA", "Integer blockId, Integer n, Bit#(6) channel", choices, 6)
    choices = [("tableId == %d" % table, "pack(inputValue)", [((value & 255), int(model.tables[table, value + 128])) for value in range(-128, 128)]) for table in range(6)]
    lines += bsv_rom("nonlinearLookup", "Integer tableId, Int#(8) inputValue", choices, 8)
    lines += ["endpackage", ""]
    (GENERATED / "SwayParameters.bsv").write_text("\n".join(lines))


def write_hex(path, values):
    Path(path).write_text("".join("%02x\n" % (int(value) & 255) for value in np.asarray(values).reshape(-1)))


def arithmetic_checks(model):
    from integer_model import divide_even, rescale
    numerators = np.arange(-65536, 65537, dtype=np.int64)
    for denominator in [1, 2, 3, 7, 16, 20, 255, 5100, 81600]:
        expected = np.rint(numerators.astype(np.float64) / denominator).astype(np.int64)
        if not np.array_equal(divide_even(numerators, denominator), expected):
            raise AssertionError("Signed ties-even division mismatch")
    for shift in range(-16, 17):
        expected = np.rint(numerators.astype(np.float64) * (2.0 ** shift)).astype(np.int64)
        if not np.array_equal(rescale(numerators, shift, 0), expected):
            raise AssertionError("Signed ties-even shift mismatch")
    for block in range(2):
        for constant in [-128, -1, 0, 1, 127]:
            value = np.full((1, 1, 20), constant, dtype=np.int64)
            prefix = "blocks.%d" % block
            from integer_model import requantize
            expected = requantize(model.parameters[prefix + ".normBias"], model.exponent(prefix + ".normBias"), model.exponent(prefix + ".norm"))
            if not np.array_equal(model.normalization(value, prefix)[0, 0], expected):
                raise AssertionError("Constant range normalization mismatch")
    return {"signedDivision": "1179657 numerator/divisor cases passed", "signedRescale": "4325409 value/shift cases passed", "constantNormalization": "10 cases passed"}


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--data", type=Path)
    parser.add_argument("--batch-size", type=int, default=128)
    parser.add_argument("--export", type=Path, default=EXPORT)
    args = parser.parse_args()
    GENERATED.mkdir(parents=True, exist_ok=True)
    tables, table_metadata = make_tables(args.export)
    np.save(GENERATED / "nonlinear_tables.npy", tables, allow_pickle=False)
    model = IntegerModel(args.export, tables)
    write_bsv(model)
    report = {"schemaVersion": 1, "exportManifestSHA256": file_hash(args.export / "manifest.json"),
              "quantizationSHA256": file_hash(args.export / "quantization.json"), "checkpointSHA256": file_hash(ROOT / "sw/results/mars_seed20260917/best.pt"),
              "parameterCount": model.manifest["parameterCount"], "parameterVerification": "All binary SHA256, size, shape, and hex values matched SW manifest",
              "nonlinearROM": table_metadata, "arithmeticChecks": arithmetic_checks(model),
              "normalization": "Exact rational (20*x-sum)*gamma/(20*(max-min))+beta, then one ties-even INT8 requantization; constant input returns requantized beta",
              "state": "INT24 current state; output before arithmetic right shift by 7 into INT17 retained state; reset per frame",
              "testTuning": False, "rtlScope": "This report evaluates the integer software reference. RTL verification is reported separately."}
    if args.data:
        features_path = args.data / "featuremap_test.npy"
        labels_path = args.data / "labels_test.npy"
        previous = json.loads((args.export.parent / "metrics.json").read_text())
        for path in [features_path, labels_path]:
            if file_hash(path) != previous["dataset_test_sha256"][path.name]:
                raise ValueError("Test dataset differs from existing SW evaluation: " + str(path))
        features = np.asarray(np.load(features_path, allow_pickle=False), dtype=np.float32)
        labels = np.asarray(np.load(labels_path, allow_pickle=False), dtype=np.float32)
        # Frames 49 and 249 exercise observed float-QDQ/rational-norm differences.
        # Fixture selection affects verification coverage only, never arithmetic.
        indices = [0, 1, 49, 249, 1023, 2047, 4095, 7983]
        fixtures = [quantize_input(features[index], model.exponent("input")) for index in indices]
        fixtures += [np.zeros((8, 8, 5), dtype=np.int64), np.full((8, 8, 5), -128, dtype=np.int64),
                     np.full((8, 8, 5), 127, dtype=np.int64), np.where(np.arange(320).reshape(8, 8, 5) % 2, 127, -128)]
        fixtures += [fixtures[0].copy(), fixtures[0].copy()]
        inputs = np.stack(fixtures)
        trace = {}
        expected = model.forward_integer(inputs, trace)
        if not np.array_equal(expected[0], expected[-1]) or not np.array_equal(expected[0], expected[-2]):
            raise AssertionError("Reference frame reset failure")
        np.savez_compressed(GENERATED / "test_trace.npz", **trace)
        write_hex(GENERATED / "test_input.hex", inputs)
        write_hex(GENERATED / "test_expected.hex", expected)
        (GENERATED / "GeneratedTestConfig.bsv").write_text("package GeneratedTestConfig;\n\ntypedef %d TestFrameCount;\n\nfunction String testInputPath();\n\treturn \"generated/test_input.hex\";\nendfunction\n\nfunction String testExpectedPath();\n\treturn \"generated/test_expected.hex\";\nendfunction\n\nendpackage\n" % len(fixtures))
        report["fixtures"] = {"count": len(fixtures), "realTestIndices": indices, "synthetic": ["zero", "all -128", "all +127", "alternating -128/+127", "repeat real index 0", "repeat real index 0"],
                              "inputOrder": "320 signed INT8 HWC bytes/frame", "outputOrder": "57 signed INT8 x19,y19,z19 coordinates/frame", "inputExponent": model.exponent("input"), "outputExponent": model.exponent("output")}
        started = time.perf_counter()
        predictions = []
        for start in range(0, len(features), args.batch_size):
            predictions.append(model.forward(features[start:start + args.batch_size]))
        predictions = np.concatenate(predictions)
        elapsed = time.perf_counter() - started
        physical = predictions.astype(np.float64) * 2.0 ** model.exponent("output")
        existing = np.load(args.export.parent / "predictions_int8_ptq.npy", allow_pickle=False)
        existing_int = np.rint(existing.astype(np.float64) / 2.0 ** model.exponent("output")).astype(np.int64)
        difference = predictions - existing_int
        report["fullTest"] = {"integerReference": metrics(physical, labels), "existingSwQDQ": metrics(existing, labels),
                              "evaluationSeconds": elapsed, "matchedOutputElements": int(np.count_nonzero(difference == 0)),
                              "totalOutputElements": int(difference.size), "matchedFrames": int(np.count_nonzero(np.all(difference == 0, axis=1))),
                              "maxOutputDifferenceLSB": int(np.abs(difference).max()), "meanAbsoluteOutputDifferenceLSB": float(np.abs(difference).mean()),
                              "differenceRMSE_cm": float(np.sqrt(np.mean((physical - existing) ** 2)) * 100.0),
                              "comparison": "Integer rational normalization replaces float32 QDQ normalization; no blanket bit-exact SW claim"}
        report["datasetSHA256"] = {path.name: file_hash(path) for path in [features_path, labels_path]}
        np.save(GENERATED / "predictions_integer.npy", predictions.astype(np.int8), allow_pickle=False)
        # Compare the 14 exact fixture inputs against the existing QDQ graph.
        import torch
        from model import createModel, forwardModel
        from quantize import QuantizationObserver, quantizedForward, quantizeTensor
        checkpoint = torch.load(ROOT / "sw/results/mars_seed20260917/best.pt", map_location="cpu", weights_only=False)
        software_model = createModel(checkpoint["config"])
        software_model.load_state_dict(checkpoint["model"])
        software_model.eval()
        physical_inputs = torch.from_numpy(inputs.astype(np.float32) * 2.0 ** model.exponent("input"))
        software_outputs = quantizedForward(software_model, physical_inputs, model.profile).numpy()
        software_ints = np.rint(software_outputs / 2.0 ** model.exponent("output")).astype(np.int64)
        report["fixtureQDQComparison"] = {"matchedElements": int(np.count_nonzero(expected == software_ints)), "totalElements": int(expected.size),
                                           "maxDifferenceLSB": int(np.abs(expected - software_ints).max())}
        class RationalNormalizationObserver(QuantizationObserver):
            def rangeNorm(self, name, value, weight, bias, epsilon):
                prefix = name.rsplit(".", 1)[0]
                input_name = "embedding" if prefix == "blocks.0" else "blocks.0.residual"
                value_int = quantizeTensor(value, self.exponent(input_name)).numpy()
                normalized = model.normalization(value_int, prefix)
                return torch.from_numpy(normalized.astype(np.float32)) * 2.0 ** self.exponent(name)
        rational_matches = 0
        stored_matches = 0
        for start in range(0, len(features), args.batch_size):
            batch = torch.from_numpy(features[start:start + args.batch_size])
            with torch.no_grad():
                observer = RationalNormalizationObserver(model.profile)
                rational = forwardModel(software_model, batch, observer=observer, usePWL=True).numpy()
                original = quantizedForward(software_model, batch, model.profile).numpy()
            rational_int = np.rint(rational / 2.0 ** model.exponent("output")).astype(np.int64)
            integer_batch = predictions[start:start + args.batch_size]
            rational_matches += int(np.count_nonzero(rational_int == integer_batch))
            stored_matches += int(np.count_nonzero(original == existing[start:start + args.batch_size]))
            if not np.array_equal(rational_int, integer_batch):
                raise AssertionError("Integer reference disagrees after isolating rational normalization")
            if not np.array_equal(original, existing[start:start + args.batch_size]):
                raise AssertionError("Current SW QDQ does not reproduce saved predictions")
        report["normalizationIsolation"] = {
            "frames": len(features), "totalOutputElements": int(predictions.size),
            "integerVersusSwWithOnlyNormalizationReplacedMatches": rational_matches,
            "currentSwVersusSavedQDQMatches": stored_matches,
            "result": "All integer outputs match the existing SW graph when only its float32 range normalization is replaced by the specified exact rational normalization"
        }
    deliverables = ["SwayParameters.bsv", "nonlinear_tables.npy", "GeneratedTestConfig.bsv", "test_input.hex",
                    "test_expected.hex", "test_trace.npz", "predictions_integer.npy"]
    report["generatedSHA256"] = {name: file_hash(GENERATED / name) for name in deliverables if (GENERATED / name).is_file()}
    report["referenceSHA256"] = {name: file_hash(Path(__file__).parent / name) for name in ["integer_model.py", "generate.py"]}
    (GENERATED / "reference_report.json").write_text(json.dumps(report, indent=2, allow_nan=False) + "\n")
    print(json.dumps(report, indent=2))


if __name__ == "__main__":
    main()
