#!/usr/bin/env python3
"""Pack existing INT8 coefficient banks for the ECP5 registered-output ROM.

This representation change never trains, calibrates, or changes coefficients.
The main generate.py command calls write_native_rom after verifying the export.
"""

import argparse
import hashlib
import json
from pathlib import Path


def write_native_rom(directory, banks):
    directory = Path(directory)
    lines = ["// Generated by reference/generate_native_rom.py from verified INT8 hex banks.",
             "// Each 9-bit word contains an INT8 coefficient and one zero parity bit.",
             "function [18431:0] bank_init;", "\tinput integer bank;", "\tbegin", "\t\tcase (bank)"]
    checked = []
    for bank in banks:
        path = directory / bank["file"]
        digest = hashlib.sha256(path.read_bytes()).hexdigest()
        if digest != bank["sha256"]:
            raise ValueError("Coefficient bank hash mismatch: " + str(path))
        values = [int(value, 16) for value in path.read_text().splitlines()]
        if len(values) != bank["depth"] or not 0 < len(values) <= 2048 or any(value < 0 or value > 255 for value in values):
            raise ValueError("Invalid coefficient bank: " + str(path))
        values += [0] * (2048 - len(values))
        packed = sum(value << (9 * index) for index, value in enumerate(values))
        bank_id = bank["layer"] * 4 + bank["lane"]
        lines.append("\t\t\t%d: bank_init = 18432'h%04608x;" % (bank_id, packed))

        # DP16KD INITVAL has sixteen 18-bit payloads in 20-bit slots.
        # Decode independently using nextpnr/ecp5/bitstream.cc's word mapping.
        restored = [0] * 2048
        for block in range(64):
            chunk = sum(((packed >> ((block * 16 + row) * 18)) & ((1 << 18) - 1)) << (row * 20)
                        for row in range(16))
            for row in range(16):
                for bit in range(18):
                    restored[block * 32 + row * 2 + bit // 9] |= ((chunk >> (20 * row + bit)) & 1) << (bit % 9)
        if restored != values:
            raise AssertionError("Native coefficient INITVAL mapping mismatch")
        checked.append({"layer": bank["layer"], "lane": bank["lane"], "sourceSHA256": digest})
    if sorted(bank["layer"] * 4 + bank["lane"] for bank in banks) != list(range(44)):
        raise ValueError("Expected all 44 distinct coefficient banks")
    lines += ["\t\t\tdefault: bank_init = 0;", "\t\tendcase", "\tend", "endfunction", ""]
    filename = "SwayCoeffRomInit.vh"
    (directory / filename).write_text("\n".join(lines))
    return {"file": filename, "primitive": "DP16KD", "dataWidth": 9, "depth": 2048,
            "outputMode": "OUTREG", "bankId": "layer*4+lane", "banksChecked": checked,
            "mapping": "INITVAL has sixteen 18-bit payloads in 20-bit slots; each payload holds two 9-bit words",
            "paddedBytesChecked": 44 * 2048}


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--generated", type=Path, default=Path(__file__).resolve().parents[1] / "generated")
    args = parser.parse_args()
    report = json.loads((args.generated / "reference_report.json").read_text())
    result = write_native_rom(args.generated, report["linearROMBanks"]["banks"])
    print("Verified and packed %d coefficient bytes into %s" % (result["paddedBytesChecked"], result["file"]))


if __name__ == "__main__":
    main()
